Add debugging output to add listing image workflow

diff --git a/.github/workflows/add-listing-image.yaml b/.github/workflows/add-listing-image.yaml
--- a/.github/workflows/add-listing-image.yaml
+++ b/.github/workflows/add-listing-image.yaml
@@ -73,9 +73,19 @@ jobs:
           image_medium="static/images/medium_$item_number.png"
           image_big="static/images/big_$item_number.png"
 
-          mogrify -path "static/images" -resize 640x640 "$image_small"
-          mogrify -path "static/images" -resize 1024x1024 "$image_medium"
-          mogrify -path "static/images" -resize 1920x1920 "$image_big"
+          echo "Debugging: Image paths: $image_small; $image_medium; image_big"
+
+          if ! mogrify -path "static/images" -resize 640x640 "$image_small"; then
+            echo "Error: Failed to resize image to small size."
+          fi
+
+          if ! mogrify -path "static/images" -resize 1024x1024 "$image_medium"; then
+            echo "Error: Failed to resize image to medium size."
+          fi
+
+          if ! mogrify -path "static/images" -resize 1920x1920 "$image_big"; then
+            echo "Error: Failed to resize image to big size."
+          fi
 
           echo "Before updating XML, current content:"
           cat $xml_path
