Add input validation to create listing workflow
and fix image default in Js

diff --git a/.github/workflows/create-listing.yaml b/.github/workflows/create-listing.yaml
--- a/.github/workflows/create-listing.yaml
+++ b/.github/workflows/create-listing.yaml
@@ -4,6 +4,8 @@ on:
     inputs:
       item_number:
         required: true
+        type: string
+        description: "Do not use these characters: <, >, &, \", ', \\ "
       category:
         required: true
         type: choice
@@ -14,21 +16,42 @@ on:
           - 'other'
       description:
         required: true
+        type: string
+        description: "Do not use these characters: <, >, &, \", ', \\ "
         default: 'Description coming soon.'
       price:
         required: true
+        type: number
+        description: 'Numbers only'
         default: 0
       is_sold:
         required: true
-        default: 'false'
         type: choice
         options:
           - 'true'
           - 'false'
+        default: 'false'
 jobs:
   update_xml:
     runs-on: ubuntu-latest
     steps:
+      - name: validate inputs
+        run: |
+          if [[ ${{ github.event.inputs.item_number }} =~ [<>&"'\\] ]] then
+            echo "Error: 'item_number' must not include special characters."
+            exit 1
+          fi
+
+          if [[ ${{ github.event.inputs.description }} =~ [<>&"'\\] ]] then
+            echo "Error: 'description' must not include special characters."
+            exit 1
+          fi
+
+          if ! [[ ${{ github.event.inputs.price }} =~ ^\d+$ ]]
+            echo "Error: 'price' must be a valid number."
+            exit 1
+          fi
+
       - name: Checkout repository
         uses: actions/checkout@v6
       
